[package]
name = "rpi-led-cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ctrlc = "3.4"
rppal = "0.17.1"
clap = { version = "4.0", features = ["derive"] }
